server:
  port: 4760
spring:
  cloud:
    gateway:
      routes:
        - id: hm-api-interface
          uri: http://www.baidu.com:4768 # todo
          predicates:
            - Path=/api/**
  redis:
    port: 6379
    host: www.baidu.com # todo
    database: 0
logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace

dubbo:
  application:
    qosEnable: false
    enable-file-cache: false
    name: dubbo-springboot-demo-provider
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    address: nacos://服务器内网或私有ip:8848 # todo
#自定义需修改
#    username: xxxxx
#    password: xxxxx