spring:
  application:
    name: hm-api-backend
  # DataSource Config todo：上线修改
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://www.baidu.com:3306/hm_api
    username: root
    password: 123456
  mvc:
    path match:
      matching-strategy: ANT_PATH_MATCHER
  # 指定文件上传大小
  servlet:
      multipart:
        max-file-size: 5MB
        max-request-size: 5MB
  # session 失效时间（分钟）
  session:
    timeout: 86400
    store-type: redis
  # redis 配置  todo: 上线修改
  redis:
    port: 6379
    host: www.baidu.com
    database: 0
#  邮箱配置 todo: 上线修改
  mail:
    host: smtp.qq.com
    username: 483489278@qq.com
    password: zlxxxxxhcbcf # 授权码
    emailFrom: 483489278@qq.com
    properties:
      mail:
        smtp:
          ssl:
            enable: true
    port: 465
  #配置阿里云oss
  aliyun:
    oss:
      end-point: oss-cnxxxxxcs.com # oss对外服务的访问域名
      access-key: LTAI5xxxxpHb6s # 你的accessKey id
      secret-key: 8U51wGuMF7xxxxwx2 # 你的accessKey secret
      bucket: mymxxxxxes # 你的bucket名称
server:
  port: 4764
  address: 0.0.0.0
  servlet:
    context-path: /api
    session:
      cookie:
        # 一周
        max-age: 604800
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

# 腾讯云cos配置
cos:
  client:
    accessKey: AKIDcKxxxxxxdrqliV5 # 你的accessKey id
    secretKey: a5WouxpxxxxxHpESXaaP0 # 你的accessKey secret
    region: xxxxxx # 区域
    bucket: xxxxxxxxxxx # 存储桶名称
# 微信支付配置
wx:
  pay:
    appId: wxxxxxxxxx67e8dc # 你的appId
    mchId: 1x0xxxx68 # 你的商户号
    apiV3Key: xxxxxbxxx3xxxx3xxx4 # 你的apiV3Key
    privateKeyPath: classpath:/pem/apiclient_key.pem # 你的私钥路径
    privateCertPath: classpath:/pem/apiclient_cert.pem # 你的私钥证书路径
    notifyUrl: https://beloved-massive-sheepdog.ngrok-free.app/api/order/notify/order # 你的回调地址
# 支付宝支付配置
alipay:
  appId: 2xxxxxxxxxxx8
  sellerId: 2xxxxxxxxxxxxx7
  notifyUrl: https://beloved-massive-sheepdog.ngrok-free.app/api/order/notify/order
  returnUrl: http://localhost:8000/account/center
  private-key: xxxxxxxxxx
  ali-pay-public-key: xxxxxxxxxxxxxxxx
dubbo:
  application:
    enable-file-cache: false
    name: dubbo-springboot-demo-provider
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    address: nacos://服务器内网或私有ip:8848 # todo:上线修改
    username: nacos
    password: xxxxxx
# 绘梦-API-SDK 配置，如需使用自己的网关host需修改
hm:
  api:
    client:
      access-key: d727b81xxxx2a5fcd91
      secret-key: 72c33a89f6xxxxx79231ed
      # 本地网关地址，可修改为自己的网关，用于本地测试，线上网关地址等
    # host: http://localhost:8090/api
