server:
  port: 4768
  servlet:
    context-path: /api
spring:
  profiles:
    active: dev
  mvc:
    path match:
      matching-strategy: ant_path_matcher
hm:
  api:
    client:
      access-key: d727b8105xxxx052a5fcd91
      secret-key: 72c33a89f6bxxxx3c5b879231ed

